name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: 
        cd avl 
        cargo test --verbose
    - name: Build
      run:
        cd main
        cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: main/target/release/main.exe
        asset_name: avl-tree-gui
        tag: ${{ github.ref }}
        overwrite: true
        body: "Release"


